# Generated by Django 3.0.6 on 2020-12-23 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('externos', '0002_auto_20201223_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convenios',
            name='dependencia',
        ),
        migrations.RemoveField(
            model_name='planificacion',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='planificacion',
            name='departamentof',
        ),
        migrations.DeleteModel(
            name='Comunicaciones',
        ),
        migrations.DeleteModel(
            name='convenios',
        ),
        migrations.DeleteModel(
            name='EntidadExterna',
        ),
        migrations.DeleteModel(
            name='planificacion',
        ),
    ]
