# Generated by Django 3.0.6 on 2020-12-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('externos', '0004_comunicaciones_convenios_entidadexterna_planificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenios',
            name='tipoinstituto',
            field=models.CharField(choices=[('1', 'MUNICIPIOS'), ('2', 'GAD PARROQUIALES'), ('3', 'MINISTERIOS'), ('4', 'VARIAS INSTITUCIONES'), ('5', 'CARTAS COMPROMISOS'), ('6', 'ASOCIACIONES, SINDICATOS, BARRIOS')], default='1', max_length=1, verbose_name='Tipo Institucion'),
        ),
    ]
