# Generated by Django 3.0.6 on 2020-12-23 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('externos', '0005_convenios_tipoinstituto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicaciones',
            name='contestado',
            field=models.CharField(max_length=20, verbose_name='Contestado por Oficio Nro'),
        ),
    ]
