# Generated by Django 3.0.6 on 2020-07-14 03:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name='Dependencia')),
            ],
            options={
                'verbose_name': 'Dependencia',
                'verbose_name_plural': 'Dependencias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='rinternos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secuencia', models.PositiveIntegerField(default=0)),
                ('fechaingreso', models.DateField(verbose_name='Fecha')),
                ('guianro', models.CharField(blank=True, max_length=40, null=True, verbose_name='Nro Memo/Oficio')),
                ('remite', models.CharField(max_length=200, verbose_name='Remitente')),
                ('dependencia', models.CharField(default='Externa', max_length=250, null=True, verbose_name='Dependencia')),
                ('descripcion', models.TextField(max_length=500, verbose_name='Descripcion')),
                ('nrotramite', models.CharField(blank=True, max_length=30, null=True, verbose_name='Tramite Interno')),
                ('fechadespacho', models.DateField(blank=True, null=True, verbose_name='Fecha Despacho')),
                ('enviadoa', models.TextField(blank=True, max_length=250, null=True, verbose_name='Enviado a')),
                ('observacion', ckeditor.fields.RichTextField(blank=True, max_length=500, null=True, verbose_name='Observacion')),
                ('atendido', models.BooleanField(default=False, verbose_name='Atendido')),
                ('documentos', models.FileField(blank=True, null=True, upload_to='media')),
            ],
            options={
                'verbose_name': 'Tramite Internos',
                'verbose_name_plural': 'Tramites Internos',
                'ordering': ['-fechaingreso'],
            },
        ),
    ]
